### ISSUE TITLE
Product Page

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#1]
## Value Statement
As a **user**,
I need **a product gallery page**,
so that **I can see a picture of the product and read its name and its amount of virtual water**.

## Description (Text, Scribble, Wireframe, Design)

<img width="339" alt="Screenshot 2020-11-20 at 10 22 56" src="https://user-images.githubusercontent.com/71647807/99783329-94c4c680-2b1a-11eb-9b37-3f4133fd88bd.png">

## Acceptance Criteria
- [x] The page displays an image of the product.
- [x] The page displays the name of the product.
- [x] The page displays the amount of virtual water of the product.

## Tasks
- [x] Create feature branch
- [x] Create product page
- [x] Create info component
- [x] Write API fetch for image
- [x] Write API fetch for product
- [x] Add styles
- [x] Config Styleguidist 
- [x] Create product page in Styleguidist 
- [x] Create info component in Styleguidist
- [x] Write product page tests
- [x] Write info component tests

## Complexity
medium
