### ISSUE TITLE
Product Search

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#10]
## Value Statement
As a **user**,
I need **a product search**,
so that **I can search products in the database**.

## Description (Text, Scribble, Wireframe, Design)
<img width="380" alt="Screenshot 2020-11-30 at 12 55 42" src="https://user-images.githubusercontent.com/71647807/100607581-72495f00-330b-11eb-9b64-ad68fef864ff.png">

## Acceptance Criteria
- [x] API endpoint can be fetched
- [x] user can input his search param in the search bar
- [x] user receives a list of results matching the search param
- [x] user can click a search result to view the product page

## Tasks
- [x] create feature branch
- [x] write backend endpoint with query logic
- [x] create search bar component
- [x] create result list component
- [x] add styling
- [x] create components in styleguidist
- [x] write component tests

## Complexity
large
