### ISSUE TITLE
API Pagination

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#14]
## Value Statement
As a **user**,
I need **paged API request results**,
so that **the app runs smoothly**.

## Description (Text, Scribble, Wireframe, Design)
API pagination (BE) and fetch (FE)

## Acceptance Criteria
- [ ] API returns request results split up in pages
- [ ] Fetches work smoothly

## Tasks
- [ ] Implement pagination logic (BE)
- [ ] Adjust fetches (FE)
- [ ] Adjust tests (FE)

## Complexity
medium
