### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#15]
## Value Statement
As a **user**,
I need **an intuitive and appealing design**,
so that **I enjoy using the app**.

## Description (Text, Scribble, Wireframe, Design)
Improve design (Adobe XD)

## Acceptance Criteria
- [ ] App can be used intuitivly
- [ ] Design is appealing

## Tasks
- [ ] improve design (Adobe XD)

## Complexity
medium
