### ISSUE TITLE
Navigation Bar and Landing Page

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#16]
## Value Statement
As a **user**,
I need **a navbar and a landing page**,
so that **I can navigate between the different pages of the app**.

## Description (Text, Scribble, Wireframe, Design)
<img width="390" alt="Screenshot 2020-12-07 at 11 01 42" src="https://user-images.githubusercontent.com/71647807/101337187-aa0c5580-387b-11eb-88ee-d1522dc28549.png">

## Acceptance Criteria
- [ ] User is welcomed on a landing page
- [ ] User can navigate to the gallery, the search page and the landing page

## Tasks
- [ ] Create new branch
- [ ] Create landing page component
- [ ] Create navbar with icons

## Complexity
small
