### ISSUE TITLE
Product Gallery

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#2]
## Value Statement
As a **user**,
I need **a product gallery**,
so that **I can see various product pages (picture, name, water) and switch between them**.

## Description (Text, Scribble, Wireframe, Design)

<img width="940" alt="Screenshot 2020-11-20 at 12 38 50" src="https://user-images.githubusercontent.com/71647807/99796230-68ff0c00-2b2d-11eb-91fd-94918d959f7a.png">

## Acceptance Criteria
- [x] The gallery displays various product pages (name, image, amount of water).
- [x] The user navigates between the products by swyping horizontally.

## Tasks
- [x] Create feature branch
- [x] Iterate product component
- [x] Implement swipe logic
- [x] Add styles
- [x] Add component tests

## Complexity
small
