### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#20]
## Value Statement
As a **web developer**,
I need **to test my code**,
so that **I can be sure that my app is working**.

## Description (Text, Scribble, Wireframe, Design)

refactor and add unit tests
end-to-end testing

## Acceptance Criteria
- [ ] all tests work and pass

## Tasks
- [ ] Refactor existing unit tests
- [ ] Add missing unit tests
- [ ] Add cypress tests

## Complexity
large
