### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#24]
## Value Statement
As a **web developer**,
I need **to refactor my code**,
so that **I have clean and meaningfull code**.

## Description (Text, Scribble, Wireframe, Design)
refactor code...

## Acceptance Criteria
- [ ] Clean code
- [ ] All features are working
- [ ] All tests pass

## Tasks

- [ ] Create HOC for error handling
- [ ] Create and update .env files
- [ ] Cleanup and order code
- [ ] Implement further points from public code review
- [ ] README: app description and screenshots, how-to env files

## Complexity
medium
