### ISSUE TITLE
Info Page

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#25]
## Value Statement
As a **user**,
I need **an info page**,
so that **I get answers to my questions**.

## Description (Text, Scribble, Wireframe, Design)
<img width="364" alt="Screenshot 2020-12-16 at 08 33 04" src="https://user-images.githubusercontent.com/71647807/102318285-5e436580-3f79-11eb-8821-3db6666e6037.png">

## Acceptance Criteria
- [ ] the page can be cisited via navigation
- [ ] when the user clicks on a question the answer opens
- [ ] another click closes the answer 

## Tasks
- [ ] Create InfoPage
- [ ] Create question / answer component
- [ ] Write toggle logic

## Complexity
small
