### ISSUE TITLE
Import CSV Data for Products

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#3]
## Value Statement
As a **user**,
I need **a csv data import**,
so that **I can see all the products from the csv file in the product gallery**.

## Description (Text, Scribble, Wireframe, Design)

<img width="924" alt="Screenshot 2020-11-20 at 13 26 50" src="https://user-images.githubusercontent.com/71647807/100580915-153bb200-32e7-11eb-8838-a3693a7fe549.png">

## Acceptance Criteria
- [x] The API can be fetched
- [x] All products are displayed in the gallery (with name, image and average water)

**The API includes:**
- [x] id
- [x] product name
- [x] average water
- [x] blue water
- [x] green water
- [x] grey water

## Tasks
- [x] Create Console Command to import CSV data (BE)
- [x] Adjust Product Entity (BE)
- [x] Adjust fetch (FE)

## Complexity
medium
