### ISSUE TITLE
Fetch Products API

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#4]
## Value Statement
As a **user**,
I need **access to all products from the database**,
so that **I can see all products (picture, name, water) in the product gallery**.

## Description (Text, Scribble, Wireframe, Design)

<img width="924" alt="Screenshot 2020-11-20 at 13 26 50" src="https://user-images.githubusercontent.com/71647807/99800093-1e34c280-2b34-11eb-92a4-3ce76ba15d92.png">

## Acceptance Criteria
- [ ] The gallery iterates on all products available in the database.
- [ ] Each product page displays an image, the name and the amount of water of the product.

## Tasks
- [ ] Write fetch for products API
- [ ] Iterate product page component on products
- [ ] Test and adjust image fetch with product name from API
- [ ] Add default image, if keyword can't be fetched
- [ ] Adjust styles
- [ ] Adjust component in Styleguidist
- [ ] Write new tests for product page component

## Complexity
medium
