### ISSUE TITLE
Technical Setup

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#5]
## Value Statement
As a **web developer**,
I need **a technical setup**,
so that **I can develop my app**.

## Description (Text, Scribble, Wireframe, Design)
- Setup BE and FE
- BE: endpoints for products and product-id 
- FE: fetches for APIs

## Acceptance Criteria
- [x] API endpoints work
- [x] APIs are fetched in React App

## Tasks
- [x] React Basis Setup
- [x] Symfony Basis Setup
- [x] Write Database Entity
- [x] Write GET Controller for Entity
- [x] React fetch and display in React 

## Complexity
medium
