### ISSUE TITLE
Dynamic URL Routing

### ISSUE THREAD

**Issue by janabremer** [janabremer/capstone-project#9]
## Value Statement
As a **user**,
I need **dynamic urls**,
so that **I can share or boookmark the link to a specific product page**.

## Description (Text, Scribble, Wireframe, Design)
Dynamic urls for product gallery pages

## Acceptance Criteria
- [x] dynamic url with id for every product page

## Tasks
- [x] Research: Dynamic url with scrolling
- [x] Implement routing logic
- [x] Adjust tests

## Complexity
medium
